version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install -g @angular/cli@6.2.2
      - npm install
  build:
    commands:
      - ng build --configuration=$BUILD_ENV --build-optimizer --base-href "/codenebula.net-front-end/"
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET_NAME --delete
